/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerLoginAdm;
import javax.swing.JTextField;

/**
 *
 * @author Lorenzo
 */
public class LoginFrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrameAdmin
     */
    public LoginFrameAdmin() {
       initComponents();
        c = new ControllerLoginAdm(this);
    }

    public JTextField getTxtCPFAdmin() {
        return txtCPFAdmin;
    }

    public void setTxtCPFAdmin(JTextField txtCPFAdmin) {
        this.txtCPFAdmin = txtCPFAdmin;
    }

    public JTextField getTxtSenhaAdmin() {
        return txtSenhaAdmin;
    }

    public void setTxtSenhaAdmin(JTextField txtSenhaAdmin) {
        this.txtSenhaAdmin = txtSenhaAdmin;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNinja = new javax.swing.JLabel();
        lblCripito = new javax.swing.JLabel();
        lblAddmin = new javax.swing.JLabel();
        lblCPFAdmin = new javax.swing.JLabel();
        txtCPFAdmin = new javax.swing.JTextField();
        lblSenhaAdmin = new javax.swing.JLabel();
        txtSenhaAdmin = new javax.swing.JTextField();
        lblLoginAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNinja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNinja.setText("       Ninja Bank");

        lblCripito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCripito.setText("Cripito Exchange");

        lblAddmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddmin.setText("Login De Administrador ");

        lblCPFAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCPFAdmin.setText("    CPF:");

        txtCPFAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFAdminActionPerformed(evt);
            }
        });

        lblSenhaAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenhaAdmin.setText(" SENHA:");

        txtSenhaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaAdminActionPerformed(evt);
            }
        });

        lblLoginAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoginAdmin.setText("Login");
        lblLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLoginAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNinja, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCripito, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(lblAddmin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblSenhaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(lblCPFAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCPFAdmin)
                                .addComponent(txtSenhaAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNinja, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCripito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPFAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPFAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFAdminActionPerformed
       
    }//GEN-LAST:event_txtCPFAdminActionPerformed

    private void txtSenhaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaAdminActionPerformed

    private void lblLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLoginAdminActionPerformed
  
    }//GEN-LAST:event_lblLoginAdminActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrameAdmin().setVisible(true);
//            }
//        });
//    }

     private ControllerLoginAdm c;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddmin;
    private javax.swing.JLabel lblCPFAdmin;
    private javax.swing.JLabel lblCripito;
    private javax.swing.JButton lblLoginAdmin;
    private javax.swing.JLabel lblNinja;
    private javax.swing.JLabel lblSenhaAdmin;
    private javax.swing.JTextField txtCPFAdmin;
    private javax.swing.JTextField txtSenhaAdmin;
    // End of variables declaration//GEN-END:variables
}
